create table car (
	id BIGSERIAL NOT NULL PRIMARY KEY 
	make VARCHAR(100) NOT NULL, 
	model VARCHAR(100) NOT NULL,
	price NUMERIC(19,2) NOT NULL
);

insert into car (make, model, price) values ('Mitsubishi', 'Starion', '98737.48');
insert into car (make, model, price) values ('Ford', 'LTD', '29127.55');
insert into car (make, model, price) values ('Pontiac', 'LeMans', '22684.26');
insert into car (make, model, price) values ('Subaru', 'Impreza', '90541.65');
insert into car (make, model, price) values ('Pontiac', '1000', '25750.22');
insert into car (make, model, price) values ('Ford', 'Econoline E350', '77381.81');
insert into car (make, model, price) values ('Mitsubishi', 'Challenger', '37808.21');
insert into car (make, model, price) values ('Volkswagen', 'rio', '22681.17');
insert into car (make, model, price) values ('Toyota', 'Highlander', '54266.08');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '61275.03');
insert into car (make, model, price) values ('Ford', 'Laser', '95719.98');
insert into car (make, model, price) values ('Lexus', 'GS', '56913.54');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '18666.56');
insert into car (make, model, price) values ('Lamborghini', 'Murciélago', '29426.83');
insert into car (make, model, price) values ('Rolls-Royce', 'Phantom', '62428.49');
insert into car (make, model, price) values ('Chevrolet', 'Astro', '99363.95');
insert into car (make, model, price) values ('Mazda', 'RX-7', '6427.38');
insert into car (make, model, price) values ('Dodge', 'D150', '17480.33');
insert into car (make, model, price) values ('Maserati', 'Quattroporte', '6584.88');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '8584.77');
insert into car (make, model, price) values ('GMC', 'Savana 1500', '74810.63');
insert into car (make, model, price) values ('Lexus', 'GS', '10960.42');
insert into car (make, model, price) values ('Aston Martin', 'V12 Vantage', '50085.42');
insert into car (make, model, price) values ('Toyota', 'Camry', '23265.58');
insert into car (make, model, price) values ('Ford', 'Th!nk', '45262.61');
insert into car (make, model, price) values ('Eagle', 'Vision', '77352.17');
insert into car (make, model, price) values ('GMC', 'Yukon', '92526.30');
insert into car (make, model, price) values ('Toyota', 'Camry', '88359.00');
insert into car (make, model, price) values ('Mercury', 'Topaz', '43834.91');
insert into car (make, model, price) values ('Ford', 'F-Series', '99223.03');
insert into car (make, model, price) values ('Volkswagen', 'GLI', '79527.09');
insert into car (make, model, price) values ('Isuzu', 'Oasis', '58158.56');
insert into car (make, model, price) values ('Honda', 'Passport', '18003.16');
insert into car (make, model, price) values ('Bentley', 'Continental Super', '22176.97');
insert into car (make, model, price) values ('Mazda', 'Mazda5', '51740.34');
insert into car (make, model, price) values ('Chevrolet', 'Cobalt SS', '44971.52');
insert into car (make, model, price) values ('Hyundai', 'Entourage', '36202.15');
insert into car (make, model, price) values ('Volvo', 'S40', '91400.41');
insert into car (make, model, price) values ('Hummer', 'H1', '40264.99');
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', '41150.97');
insert into car (make, model, price) values ('Pontiac', '1000', '58686.88');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '85716.59');
insert into car (make, model, price) values ('Honda', 'Accord', '32035.14');
insert into car (make, model, price) values ('Toyota', 'RAV4', '18917.89');
insert into car (make, model, price) values ('Ford', 'F150', '73072.19');
insert into car (make, model, price) values ('Ford', 'E150', '49098.12');
insert into car (make, model, price) values ('Ford', 'F150', '76983.86');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', '42299.43');
insert into car (make, model, price) values ('Isuzu', 'Trooper', '83282.57');
insert into car (make, model, price) values ('Kia', 'Sorento', '71900.63');
insert into car (make, model, price) values ('Bentley', 'Continental', '97696.22');
insert into car (make, model, price) values ('Acura', 'RL', '6780.90');
insert into car (make, model, price) values ('Mitsubishi', 'Tundra', '91808.79');
insert into car (make, model, price) values ('Cadillac', 'CTS', '5061.49');
insert into car (make, model, price) values ('Infiniti', 'G35', '83363.96');
insert into car (make, model, price) values ('Cadillac', 'CTS-V', '71290.03');
insert into car (make, model, price) values ('Ford', 'Taurus', '20534.21');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '25436.45');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '76009.64');
insert into car (make, model, price) values ('Hyundai', 'Excel', '9933.82');
insert into car (make, model, price) values ('Mazda', 'Millenia', '63015.57');
insert into car (make, model, price) values ('Nissan', 'Altima', '54994.85');
insert into car (make, model, price) values ('Subaru', 'BRZ', '35133.05');
insert into car (make, model, price) values ('Ford', 'F350', '88626.33');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '17597.03');
insert into car (make, model, price) values ('Toyota', 'Solara', '4549.81');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '26982.16');
insert into car (make, model, price) values ('Kia', 'Sephia', '41506.34');
insert into car (make, model, price) values ('Saab', '900', '64203.16');
insert into car (make, model, price) values ('Ford', 'F250', '77500.55');
insert into car (make, model, price) values ('Chrysler', 'New Yorker', '79571.29');
insert into car (make, model, price) values ('Toyota', 'T100', '65075.20');
insert into car (make, model, price) values ('Chevrolet', 'Caprice Classic', '77097.72');
insert into car (make, model, price) values ('Lexus', 'ES', '79841.05');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '59305.90');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '69559.03');
insert into car (make, model, price) values ('Chevrolet', 'G-Series G10', '92415.90');
insert into car (make, model, price) values ('Ford', 'F150', '39564.57');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '57805.83');
insert into car (make, model, price) values ('Suzuki', 'Sidekick', '23683.30');
insert into car (make, model, price) values ('Acura', 'RSX', '87696.96');
insert into car (make, model, price) values ('Pontiac', 'Solstice', '3123.64');
insert into car (make, model, price) values ('Mercury', 'Sable', '44306.08');
insert into car (make, model, price) values ('Plymouth', 'Grand Voyager', '2731.18');
insert into car (make, model, price) values ('Subaru', 'B9 Tribeca', '70572.09');
insert into car (make, model, price) values ('Mitsubishi', 'Mighty Max', '99500.19');
insert into car (make, model, price) values ('Mitsubishi', 'Expo', '78422.68');
insert into car (make, model, price) values ('Acura', 'NSX', '42785.36');
insert into car (make, model, price) values ('Kia', 'Rio', '5989.42');
insert into car (make, model, price) values ('Ford', 'Focus', '13903.58');
insert into car (make, model, price) values ('Ford', 'Escort', '22899.15');
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', '47716.83');
insert into car (make, model, price) values ('Mazda', '323', '26569.67');
insert into car (make, model, price) values ('Lincoln', 'Continental', '68572.49');
insert into car (make, model, price) values ('Mercury', 'Mountaineer', '69655.70');
insert into car (make, model, price) values ('Ford', 'Explorer', '61037.97');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '13618.57');
insert into car (make, model, price) values ('Dodge', 'Avenger', '77402.15');
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', '20658.94');
insert into car (make, model, price) values ('Lexus', 'SC', '7696.48');
insert into car (make, model, price) values ('Subaru', 'Forester', '24431.41');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '47085.94');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '45832.77');
insert into car (make, model, price) values ('GMC', 'Savana 2500', '56946.54');
insert into car (make, model, price) values ('Buick', 'Park Avenue', '57590.34');
insert into car (make, model, price) values ('Toyota', 'Matrix', '31742.28');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '91601.78');
insert into car (make, model, price) values ('Suzuki', 'Swift', '25441.41');
insert into car (make, model, price) values ('Mazda', 'B-Series', '14847.78');
insert into car (make, model, price) values ('Cadillac', 'Brougham', '97764.00');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '62314.83');
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass Supreme', '70503.02');
insert into car (make, model, price) values ('Toyota', 'RAV4', '47274.64');
insert into car (make, model, price) values ('Jeep', 'Compass', '56071.17');
insert into car (make, model, price) values ('BMW', '6 Series', '86517.32');
insert into car (make, model, price) values ('Honda', 'CR-V', '43092.76');
insert into car (make, model, price) values ('Pontiac', 'Montana', '66448.83');
insert into car (make, model, price) values ('Chrysler', 'Aspen', '89098.76');
insert into car (make, model, price) values ('Suzuki', 'Grand Vitara', '94517.25');
insert into car (make, model, price) values ('Mitsubishi', 'Diamante', '50878.58');
insert into car (make, model, price) values ('Ford', 'Bronco', '90791.93');
insert into car (make, model, price) values ('Ford', 'Econoline E250', '34485.39');
insert into car (make, model, price) values ('Acura', 'RL', '25043.51');
insert into car (make, model, price) values ('Lamborghini', 'Gallardo', '90222.95');
insert into car (make, model, price) values ('Toyota', 'Previa', '13749.37');
insert into car (make, model, price) values ('Nissan', 'Armada', '84208.60');
insert into car (make, model, price) values ('Ford', 'Expedition', '75695.25');
insert into car (make, model, price) values ('Pontiac', 'Sunbird', '27579.60');
insert into car (make, model, price) values ('Mercedes-Benz', '400E', '44007.82');
insert into car (make, model, price) values ('Buick', 'Regal', '94041.21');
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', '64523.45');
insert into car (make, model, price) values ('Chevrolet', 'Equinox', '93051.11');
insert into car (make, model, price) values ('Toyota', 'Sienna', '52897.05');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '35935.50');
insert into car (make, model, price) values ('Ford', 'EXP', '81119.49');
insert into car (make, model, price) values ('Lexus', 'ES', '78907.57');
insert into car (make, model, price) values ('Mercedes-Benz', 'G55 AMG', '35581.46');
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', '98307.80');
insert into car (make, model, price) values ('Lamborghini', 'Diablo', '57669.36');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '40546.79');
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', '39633.72');
insert into car (make, model, price) values ('Lexus', 'LS', '19792.27');
insert into car (make, model, price) values ('Nissan', 'Armada', '94797.38');
insert into car (make, model, price) values ('Nissan', 'Altima', '77351.85');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '26921.17');
insert into car (make, model, price) values ('Maybach', 'Landaulet', '32274.42');
insert into car (make, model, price) values ('Mazda', 'Mazda3', '42212.09');
insert into car (make, model, price) values ('Lincoln', 'Continental', '24134.70');
insert into car (make, model, price) values ('Infiniti', 'G', '40555.22');
insert into car (make, model, price) values ('Lexus', 'RX', '16825.94');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', '40462.22');
insert into car (make, model, price) values ('Plymouth', 'Laser', '81402.99');
insert into car (make, model, price) values ('Suzuki', 'Grand Vitara', '23616.78');
insert into car (make, model, price) values ('Toyota', 'Corolla', '26276.90');
insert into car (make, model, price) values ('Acura', 'RDX', '80387.80');
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass Supreme', '64352.27');
insert into car (make, model, price) values ('Lexus', 'LX', '4654.18');
insert into car (make, model, price) values ('GMC', 'Jimmy', '72360.80');
insert into car (make, model, price) values ('BMW', '5 Series', '37763.27');
insert into car (make, model, price) values ('Maserati', 'Spyder', '59618.27');
insert into car (make, model, price) values ('Mercury', 'Tracer', '91381.92');
insert into car (make, model, price) values ('Chevrolet', 'S10', '5757.84');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '83009.54');
insert into car (make, model, price) values ('Buick', 'Skylark', '71203.29');
insert into car (make, model, price) values ('Ford', 'Crown Victoria', '2262.11');
insert into car (make, model, price) values ('Nissan', 'NX', '11403.14');
insert into car (make, model, price) values ('Volkswagen', 'Corrado', '72887.82');
insert into car (make, model, price) values ('Chevrolet', 'G-Series G30', '67098.01');
insert into car (make, model, price) values ('Dodge', 'Viper', '2187.30');
insert into car (make, model, price) values ('Toyota', 'Prius', '73875.57');
insert into car (make, model, price) values ('GMC', 'Suburban 1500', '14308.41');
insert into car (make, model, price) values ('Dodge', 'Caravan', '81378.94');
insert into car (make, model, price) values ('Pontiac', 'Sunbird', '37312.44');
insert into car (make, model, price) values ('Ford', 'Expedition', '95157.31');
insert into car (make, model, price) values ('Lincoln', 'Navigator', '2422.67');
insert into car (make, model, price) values ('Saturn', 'L-Series', '79924.99');
insert into car (make, model, price) values ('Ford', 'F-Series', '80454.49');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '74412.70');
insert into car (make, model, price) values ('Volkswagen', 'riolet', '54724.14');
insert into car (make, model, price) values ('Chevrolet', 'Silverado', '90403.80');
insert into car (make, model, price) values ('Land Rover', 'Discovery', '20698.98');
insert into car (make, model, price) values ('Ford', 'Mustang', '98900.47');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '60987.41');
insert into car (make, model, price) values ('Lamborghini', 'Murciélago', '62924.78');
insert into car (make, model, price) values ('GMC', 'Sierra 3500', '77991.77');
insert into car (make, model, price) values ('Lexus', 'IS', '53679.92');
insert into car (make, model, price) values ('Oldsmobile', 'Aurora', '60575.44');
insert into car (make, model, price) values ('Volkswagen', 'CC', '88625.88');
insert into car (make, model, price) values ('Audi', 'A6', '52359.01');
insert into car (make, model, price) values ('Nissan', '300ZX', '22343.81');
insert into car (make, model, price) values ('Geo', 'Metro', '27188.98');
insert into car (make, model, price) values ('GMC', 'Savana 2500', '95661.43');
insert into car (make, model, price) values ('Plymouth', 'Prowler', '98134.35');
insert into car (make, model, price) values ('Volvo', 'S80', '49462.91');
insert into car (make, model, price) values ('Volvo', 'S70', '47183.23');
insert into car (make, model, price) values ('Geo', 'Metro', '65097.00');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '37993.40');
insert into car (make, model, price) values ('Chevrolet', 'G-Series 2500', '75540.12');
insert into car (make, model, price) values ('Lincoln', 'MKS', '3509.71');
insert into car (make, model, price) values ('Nissan', '370Z', '61449.09');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '99339.24');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '78829.20');
insert into car (make, model, price) values ('Aston Martin', 'Vanquish S', '79106.99');
insert into car (make, model, price) values ('Ford', 'Ranger', '98973.57');
insert into car (make, model, price) values ('Chrysler', 'Crossfire Roadster', '44099.46');
insert into car (make, model, price) values ('Ford', 'Contour', '87648.65');
insert into car (make, model, price) values ('Land Rover', 'Range Rover Evoque', '59509.01');
insert into car (make, model, price) values ('Saturn', 'Relay', '68853.25');
insert into car (make, model, price) values ('Buick', 'Enclave', '7044.79');
insert into car (make, model, price) values ('Jaguar', 'XK', '20313.42');
insert into car (make, model, price) values ('Ford', 'Fiesta', '35601.72');
insert into car (make, model, price) values ('Ford', 'Laser', '85001.51');
insert into car (make, model, price) values ('Audi', 'A4', '82283.71');
insert into car (make, model, price) values ('Dodge', 'Stratus', '98250.76');
insert into car (make, model, price) values ('Infiniti', 'QX', '26834.66');
insert into car (make, model, price) values ('Mercury', 'Cougar', '30754.42');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '28362.84');
insert into car (make, model, price) values ('Ford', 'Explorer', '87541.70');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', '21154.43');
insert into car (make, model, price) values ('Saturn', 'Outlook', '85258.36');
insert into car (make, model, price) values ('GMC', 'Envoy', '27930.92');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '29013.37');
insert into car (make, model, price) values ('GMC', 'Savana 2500', '73764.19');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '13103.29');
insert into car (make, model, price) values ('Nissan', '200SX', '44327.65');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '4181.66');
insert into car (make, model, price) values ('Mazda', 'MPV', '68841.19');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '75125.96');
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', '78119.12');
insert into car (make, model, price) values ('Geo', 'Tracker', '28510.09');
insert into car (make, model, price) values ('Chevrolet', 'Volt', '82960.62');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '91470.53');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '64243.34');
insert into car (make, model, price) values ('Volvo', 'S80', '27837.58');
insert into car (make, model, price) values ('Ford', 'Escape', '16289.47');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '49090.57');
insert into car (make, model, price) values ('Hyundai', 'Tiburon', '45070.75');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '56957.49');
insert into car (make, model, price) values ('Nissan', 'Sentra', '76127.62');
insert into car (make, model, price) values ('Honda', 'Civic', '52573.05');
insert into car (make, model, price) values ('Mitsubishi', 'Excel', '7605.94');
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', '55788.80');
insert into car (make, model, price) values ('Tesla', 'Model S', '34169.07');
insert into car (make, model, price) values ('Suzuki', 'XL7', '68186.75');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '54508.95');
insert into car (make, model, price) values ('Infiniti', 'FX', '28032.23');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '29646.07');
insert into car (make, model, price) values ('Pontiac', 'Fiero', '25239.83');
insert into car (make, model, price) values ('Hummer', 'H3T', '41087.81');
insert into car (make, model, price) values ('Honda', 'CR-V', '86497.20');
insert into car (make, model, price) values ('Suzuki', 'SX4', '72514.34');
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', '20544.40');
insert into car (make, model, price) values ('Ford', 'Falcon', '6180.17');
insert into car (make, model, price) values ('Volvo', 'XC70', '52630.31');
insert into car (make, model, price) values ('Chrysler', 'Grand Voyager', '69909.33');
insert into car (make, model, price) values ('Dodge', 'Dakota', '10281.72');
insert into car (make, model, price) values ('Audi', '5000CS Quattro', '25210.95');
insert into car (make, model, price) values ('Acura', 'RDX', '31936.91');
insert into car (make, model, price) values ('Toyota', 'Camry Solara', '87992.41');
insert into car (make, model, price) values ('Plymouth', 'Fury', '33574.64');
insert into car (make, model, price) values ('Lincoln', 'Navigator', '41197.13');
insert into car (make, model, price) values ('Ford', 'Econoline E250', '37948.07');
insert into car (make, model, price) values ('Pontiac', 'Vibe', '51482.33');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '29637.30');
insert into car (make, model, price) values ('Toyota', 'Sienna', '21510.25');
insert into car (make, model, price) values ('Ford', 'Falcon', '60330.21');
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', '98391.15');
insert into car (make, model, price) values ('Chevrolet', 'Lumina', '38808.97');
insert into car (make, model, price) values ('Saturn', 'S-Series', '99238.80');
insert into car (make, model, price) values ('Volkswagen', 'Corrado', '96386.62');
insert into car (make, model, price) values ('Volvo', 'V90', '54187.76');
insert into car (make, model, price) values ('Porsche', '928', '45078.15');
insert into car (make, model, price) values ('Subaru', 'Forester', '59568.32');
insert into car (make, model, price) values ('Audi', 'S4', '99964.70');
insert into car (make, model, price) values ('Mercury', 'Topaz', '70697.31');
insert into car (make, model, price) values ('Chevrolet', 'K5 Blazer', '46511.19');
insert into car (make, model, price) values ('Aston Martin', 'DB9', '31847.34');
insert into car (make, model, price) values ('GMC', 'Sierra 2500', '66864.80');
insert into car (make, model, price) values ('Mercedes-Benz', 'G-Class', '93132.50');
insert into car (make, model, price) values ('Ford', 'Expedition', '38245.84');
insert into car (make, model, price) values ('Honda', 'Prelude', '90817.38');
insert into car (make, model, price) values ('Chevrolet', 'S10', '34555.07');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '23175.47');
insert into car (make, model, price) values ('Mercury', 'Villager', '29094.37');
insert into car (make, model, price) values ('Buick', 'LeSabre', '56418.92');
insert into car (make, model, price) values ('Isuzu', 'Axiom', '79245.92');
insert into car (make, model, price) values ('Audi', 'S6', '89519.30');
insert into car (make, model, price) values ('Audi', 'RS4', '91050.65');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '22072.69');
insert into car (make, model, price) values ('Infiniti', 'QX', '38083.10');
insert into car (make, model, price) values ('Porsche', '944', '13189.00');
insert into car (make, model, price) values ('Ford', 'F450', '65814.75');
insert into car (make, model, price) values ('Buick', 'Park Avenue', '32050.69');
insert into car (make, model, price) values ('Cadillac', 'Escalade', '8268.09');
insert into car (make, model, price) values ('BMW', 'Z8', '97234.70');
insert into car (make, model, price) values ('BMW', 'X6', '60422.22');
insert into car (make, model, price) values ('Nissan', 'Quest', '90294.72');
insert into car (make, model, price) values ('Nissan', 'Frontier', '28951.62');
insert into car (make, model, price) values ('Kia', 'Rio', '83208.65');
insert into car (make, model, price) values ('Dodge', 'Caravan', '58592.51');
insert into car (make, model, price) values ('Buick', 'Reatta', '32171.28');
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', '95034.40');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '42684.33');
insert into car (make, model, price) values ('Aston Martin', 'V12 Vantage', '78184.45');
insert into car (make, model, price) values ('Oldsmobile', 'Silhouette', '24205.70');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '17420.73');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '54011.07');
insert into car (make, model, price) values ('Mazda', 'Millenia', '4424.69');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '38764.40');
insert into car (make, model, price) values ('Chevrolet', 'Express 2500', '76446.02');
insert into car (make, model, price) values ('MINI', 'Cooper', '50095.48');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '75976.47');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '4078.57');
insert into car (make, model, price) values ('Lexus', 'ES', '83208.82');
insert into car (make, model, price) values ('Volkswagen', 'Routan', '13862.61');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '25111.60');
insert into car (make, model, price) values ('Ford', 'F-Series', '57329.65');
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', '54675.18');
insert into car (make, model, price) values ('Pontiac', 'G5', '8238.43');
insert into car (make, model, price) values ('Subaru', 'Baja', '15480.34');
insert into car (make, model, price) values ('Mazda', 'MPV', '58081.21');
insert into car (make, model, price) values ('Jaguar', 'XJ Series', '72018.26');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '9606.88');
insert into car (make, model, price) values ('MINI', 'Cooper Clubman', '60266.44');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '79040.01');
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass Supreme', '10056.82');
insert into car (make, model, price) values ('Kia', 'Spectra', '97784.28');
insert into car (make, model, price) values ('Honda', 'Prelude', '59328.15');
insert into car (make, model, price) values ('Porsche', 'Boxster', '44231.42');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '79180.81');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '6107.40');
insert into car (make, model, price) values ('Lincoln', 'Mark LT', '99034.39');
insert into car (make, model, price) values ('Oldsmobile', '88', '27453.20');
insert into car (make, model, price) values ('Subaru', 'Outback', '81592.22');
insert into car (make, model, price) values ('Ferrari', '430 Scuderia', '47463.61');
insert into car (make, model, price) values ('Lexus', 'LS Hybrid', '44264.88');
insert into car (make, model, price) values ('Hyundai', 'Accent', '94584.69');
insert into car (make, model, price) values ('BMW', 'X5', '41249.27');
insert into car (make, model, price) values ('Kia', 'Sportage', '39547.34');
insert into car (make, model, price) values ('GMC', 'Sonoma', '66861.02');
insert into car (make, model, price) values ('Cadillac', 'CTS', '25400.62');
insert into car (make, model, price) values ('Nissan', 'Sentra', '7375.97');
insert into car (make, model, price) values ('Foose', 'Hemisfear', '89067.78');
insert into car (make, model, price) values ('Dodge', 'Ram 1500', '40932.62');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '39809.36');
insert into car (make, model, price) values ('Mercedes-Benz', 'G-Class', '41520.37');
insert into car (make, model, price) values ('GMC', 'Savana 3500', '22803.97');
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', '43478.52');
insert into car (make, model, price) values ('Toyota', 'MR2', '52366.51');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '74662.39');
insert into car (make, model, price) values ('Ford', 'Windstar', '24152.61');
insert into car (make, model, price) values ('Lexus', 'LS', '20998.45');
insert into car (make, model, price) values ('Ford', 'Mustang', '46610.14');
insert into car (make, model, price) values ('Chevrolet', 'Astro', '82119.56');
insert into car (make, model, price) values ('Pontiac', 'G5', '93264.90');
insert into car (make, model, price) values ('Chevrolet', '3500', '54467.50');
insert into car (make, model, price) values ('Saturn', 'Relay', '83397.83');
insert into car (make, model, price) values ('Volkswagen', 'Type 2', '86317.29');
insert into car (make, model, price) values ('Buick', 'Rendezvous', '33578.86');
insert into car (make, model, price) values ('Porsche', '911', '3765.07');
insert into car (make, model, price) values ('Subaru', 'Legacy', '61271.89');
insert into car (make, model, price) values ('Ford', 'Bronco', '10726.69');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '8991.39');
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', '78404.11');
insert into car (make, model, price) values ('BMW', '3 Series', '96882.25');
insert into car (make, model, price) values ('Land Rover', 'Defender', '72388.17');
insert into car (make, model, price) values ('Subaru', 'Justy', '87026.37');
insert into car (make, model, price) values ('Dodge', 'Sprinter', '17492.00');
insert into car (make, model, price) values ('Ferrari', '599 GTB Fiorano', '10140.86');
insert into car (make, model, price) values ('Cadillac', 'XLR-V', '84732.35');
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', '52388.98');
insert into car (make, model, price) values ('Mitsubishi', 'Raider', '57793.84');
insert into car (make, model, price) values ('Ferrari', '599 GTB Fiorano', '57352.23');
insert into car (make, model, price) values ('Chevrolet', 'Blazer', '43536.35');
insert into car (make, model, price) values ('BMW', 'X3', '87837.73');
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', '34342.26');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '54889.56');
insert into car (make, model, price) values ('GMC', '2500', '46032.20');
insert into car (make, model, price) values ('Aston Martin', 'Vantage', '96707.19');
insert into car (make, model, price) values ('Chevrolet', 'Astro', '79045.47');
insert into car (make, model, price) values ('Toyota', '4Runner', '58375.99');
insert into car (make, model, price) values ('Acura', 'RSX', '56519.63');
insert into car (make, model, price) values ('Lincoln', 'Aviator', '30604.23');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '87189.88');
insert into car (make, model, price) values ('Ford', 'Freestar', '96414.75');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '91116.09');
insert into car (make, model, price) values ('Porsche', 'Cayenne', '8037.04');
insert into car (make, model, price) values ('Saab', '9000', '78498.70');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '25050.98');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '38726.25');
insert into car (make, model, price) values ('BMW', 'Z3', '56897.90');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '40882.83');
insert into car (make, model, price) values ('Mazda', 'Tribute', '18230.76');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '85698.48');
insert into car (make, model, price) values ('Mazda', 'CX-9', '41202.98');
insert into car (make, model, price) values ('Ford', 'Mustang', '81156.28');
insert into car (make, model, price) values ('Dodge', 'Intrepid', '18893.56');
insert into car (make, model, price) values ('Mitsubishi', 'Expo', '63813.57');
insert into car (make, model, price) values ('BMW', 'X5', '4274.03');
insert into car (make, model, price) values ('Chevrolet', 'Venture', '30793.67');
insert into car (make, model, price) values ('Mercury', 'Villager', '68312.76');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '70882.01');
insert into car (make, model, price) values ('GMC', 'Savana 2500', '94462.59');
insert into car (make, model, price) values ('Audi', 'A6', '9682.01');
insert into car (make, model, price) values ('Dodge', 'Ram Van 1500', '45252.17');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '92095.10');
insert into car (make, model, price) values ('Hyundai', 'Tiburon', '32352.00');
insert into car (make, model, price) values ('Volvo', 'V40', '25038.96');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '41397.28');
insert into car (make, model, price) values ('BMW', '530', '89320.18');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '3047.99');
insert into car (make, model, price) values ('Nissan', '240SX', '60331.83');
insert into car (make, model, price) values ('Ford', 'Escort', '46366.34');
insert into car (make, model, price) values ('Chevrolet', 'G-Series G10', '8923.22');
insert into car (make, model, price) values ('Dodge', 'Intrepid', '77840.15');
insert into car (make, model, price) values ('Pontiac', '6000', '81127.24');
insert into car (make, model, price) values ('Dodge', 'Ram Van 2500', '22853.29');
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', '96570.27');
insert into car (make, model, price) values ('Land Rover', 'Freelander', '75048.23');
insert into car (make, model, price) values ('Land Rover', 'Freelander', '22775.02');
insert into car (make, model, price) values ('BMW', 'Z4', '31529.09');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '81283.13');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '26060.34');
insert into car (make, model, price) values ('Suzuki', 'SX4', '3159.55');
insert into car (make, model, price) values ('Pontiac', 'Parisienne', '96774.28');
insert into car (make, model, price) values ('Chevrolet', 'Lumina', '14401.56');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '10751.05');
insert into car (make, model, price) values ('Lexus', 'RX', '66203.32');
insert into car (make, model, price) values ('Cadillac', 'CTS', '95167.81');
insert into car (make, model, price) values ('Honda', 'Civic', '30331.15');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche', '20538.74');
insert into car (make, model, price) values ('GMC', 'Acadia', '14830.49');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '34609.43');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '81896.89');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', '64963.89');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '43904.28');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '64379.93');
insert into car (make, model, price) values ('Hummer', 'H1', '25851.34');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '74559.33');
insert into car (make, model, price) values ('Volvo', 'V40', '64292.08');
insert into car (make, model, price) values ('GMC', 'Envoy', '43769.75');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', '28134.40');
insert into car (make, model, price) values ('Mazda', 'MX-3', '4916.40');
insert into car (make, model, price) values ('Volvo', 'V70', '65792.58');
insert into car (make, model, price) values ('Volvo', 'S60', '67461.49');
insert into car (make, model, price) values ('BMW', '7 Series', '29017.17');
insert into car (make, model, price) values ('Mitsubishi', 'Sigma', '75049.80');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', '70419.50');
insert into car (make, model, price) values ('Suzuki', 'SJ 410', '84950.64');
insert into car (make, model, price) values ('Ford', 'Tempo', '71153.37');
insert into car (make, model, price) values ('Chevrolet', 'Venture', '86801.85');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '62089.52');
insert into car (make, model, price) values ('GMC', 'Envoy XUV', '87252.02');
insert into car (make, model, price) values ('Jaguar', 'S-Type', '63117.60');
insert into car (make, model, price) values ('Acura', 'SLX', '96117.12');
insert into car (make, model, price) values ('Land Rover', 'Discovery', '19458.61');
insert into car (make, model, price) values ('Audi', 'Cabriolet', '30204.01');
insert into car (make, model, price) values ('GMC', '1500 Club Coupe', '89953.72');
insert into car (make, model, price) values ('Volvo', 'S60', '90079.27');
insert into car (make, model, price) values ('Porsche', 'Boxster', '89585.34');
insert into car (make, model, price) values ('Audi', 'Cabriolet', '6653.12');
insert into car (make, model, price) values ('Nissan', 'Versa', '93711.24');
insert into car (make, model, price) values ('Ford', 'F-Series Super Duty', '74302.69');
insert into car (make, model, price) values ('Chevrolet', 'Aveo', '84977.64');
insert into car (make, model, price) values ('BMW', '530', '24925.71');
insert into car (make, model, price) values ('Chevrolet', 'Caprice', '52768.44');
insert into car (make, model, price) values ('Ford', 'LTD Crown Victoria', '62657.53');
insert into car (make, model, price) values ('Mazda', 'Tribute', '78854.00');
insert into car (make, model, price) values ('GMC', 'Savana 3500', '50169.74');
insert into car (make, model, price) values ('Subaru', 'Impreza', '97160.11');
insert into car (make, model, price) values ('Chevrolet', 'Lumina', '38452.87');
insert into car (make, model, price) values ('BMW', '6 Series', '60537.91');
insert into car (make, model, price) values ('Nissan', '300ZX', '17396.90');
insert into car (make, model, price) values ('Nissan', 'Frontier', '10044.37');
insert into car (make, model, price) values ('Mazda', 'MPV', '61806.37');
insert into car (make, model, price) values ('Isuzu', 'Hombre Space', '65761.34');
insert into car (make, model, price) values ('Chevrolet', 'G-Series G20', '45430.69');
insert into car (make, model, price) values ('Ford', 'Bronco', '77515.44');
insert into car (make, model, price) values ('Nissan', 'Rogue', '30475.49');
insert into car (make, model, price) values ('Lincoln', 'Blackwood', '46606.99');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '28861.30');
insert into car (make, model, price) values ('Ford', 'E250', '28993.33');
insert into car (make, model, price) values ('Toyota', 'Tercel', '78898.80');
insert into car (make, model, price) values ('GMC', 'Canyon', '30648.10');
insert into car (make, model, price) values ('Kia', 'Forte', '50466.78');
insert into car (make, model, price) values ('Hummer', 'H3', '93747.46');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer Evolution', '8326.89');
insert into car (make, model, price) values ('Rambler', 'Classic', '50077.48');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '69137.96');
insert into car (make, model, price) values ('Nissan', 'Quest', '99968.73');
insert into car (make, model, price) values ('Daewoo', 'Lanos', '73738.10');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '34859.36');
insert into car (make, model, price) values ('Acura', 'TSX', '75705.23');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '59752.54');
insert into car (make, model, price) values ('Nissan', 'Quest', '32454.46');
insert into car (make, model, price) values ('Pontiac', 'G5', '67896.53');
insert into car (make, model, price) values ('Dodge', 'Dakota', '15213.96');
insert into car (make, model, price) values ('Infiniti', 'I', '37286.54');
insert into car (make, model, price) values ('Saab', '900', '68722.93');
insert into car (make, model, price) values ('Ford', 'Expedition', '30517.26');
insert into car (make, model, price) values ('Ford', 'Mustang', '90792.91');
insert into car (make, model, price) values ('Ford', 'E-Series', '38391.38');
insert into car (make, model, price) values ('Chevrolet', 'Sportvan G30', '17846.56');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 2500', '26605.16');
insert into car (make, model, price) values ('Lincoln', 'MKX', '14729.09');
insert into car (make, model, price) values ('Hyundai', 'Azera', '49392.42');
insert into car (make, model, price) values ('Mazda', 'MX-5', '99367.80');
insert into car (make, model, price) values ('Suzuki', 'Reno', '8191.34');
insert into car (make, model, price) values ('GMC', 'Envoy XL', '65232.30');
insert into car (make, model, price) values ('GMC', 'Savana 3500', '72967.84');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '46888.91');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', '48825.41');
insert into car (make, model, price) values ('Pontiac', 'Sunfire', '52965.03');
insert into car (make, model, price) values ('Ford', 'E-Series', '68611.27');
insert into car (make, model, price) values ('Jaguar', 'X-Type', '81614.23');
insert into car (make, model, price) values ('Subaru', 'Legacy', '57432.82');
insert into car (make, model, price) values ('Toyota', '4Runner', '83757.01');
insert into car (make, model, price) values ('Dodge', 'Ram Van 2500', '90311.49');
insert into car (make, model, price) values ('Suzuki', 'XL-7', '91004.53');
insert into car (make, model, price) values ('GMC', 'Sierra', '69416.94');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '36522.88');
insert into car (make, model, price) values ('Jaguar', 'X-Type', '26896.39');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '44278.87');
insert into car (make, model, price) values ('Chevrolet', 'HHR', '23451.30');
insert into car (make, model, price) values ('Acura', 'NSX', '82806.62');
insert into car (make, model, price) values ('Cadillac', 'CTS', '69303.08');
insert into car (make, model, price) values ('GMC', 'Sierra 1500', '75409.32');
insert into car (make, model, price) values ('Dodge', 'Durango', '80397.50');
insert into car (make, model, price) values ('Pontiac', 'Firefly', '13953.91');
insert into car (make, model, price) values ('Subaru', 'Impreza', '73490.48');
insert into car (make, model, price) values ('Cadillac', 'Escalade ESV', '40163.53');
insert into car (make, model, price) values ('Ford', 'Expedition', '57723.53');
insert into car (make, model, price) values ('Nissan', 'Frontier', '39298.20');
insert into car (make, model, price) values ('Porsche', '911', '18934.03');
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', '4226.91');
insert into car (make, model, price) values ('Ford', 'Mustang', '20717.56');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '19088.47');
insert into car (make, model, price) values ('Ford', 'F150', '53054.01');
insert into car (make, model, price) values ('Mazda', 'CX-9', '4529.77');
insert into car (make, model, price) values ('Lexus', 'ES', '40371.75');
insert into car (make, model, price) values ('Bentley', 'Continental Flying Spur', '37879.88');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '35927.48');
insert into car (make, model, price) values ('Chevrolet', 'G-Series 2500', '78602.88');
insert into car (make, model, price) values ('GMC', 'Suburban 2500', '52315.76');
insert into car (make, model, price) values ('Lincoln', 'MKX', '61337.06');
insert into car (make, model, price) values ('Honda', 'CR-V', '44398.54');
insert into car (make, model, price) values ('Ford', 'E350', '5698.59');
insert into car (make, model, price) values ('Ford', 'F-Series Super Duty', '74036.57');
insert into car (make, model, price) values ('Eagle', 'Summit', '31549.55');
insert into car (make, model, price) values ('Mercedes-Benz', '300E', '55373.79');
insert into car (make, model, price) values ('Dodge', 'Ram Van 3500', '45694.88');
insert into car (make, model, price) values ('Porsche', '928', '6139.34');
insert into car (make, model, price) values ('GMC', 'Envoy', '52862.25');
insert into car (make, model, price) values ('Chevrolet', 'Equinox', '63016.48');
insert into car (make, model, price) values ('Buick', 'Coachbuilder', '64081.31');
insert into car (make, model, price) values ('BMW', '1 Series', '6574.40');
insert into car (make, model, price) values ('Volvo', 'C70', '26350.94');
insert into car (make, model, price) values ('Chevrolet', 'Corvair', '12544.91');
insert into car (make, model, price) values ('Chevrolet', 'Equinox', '47687.74');
insert into car (make, model, price) values ('Lincoln', 'Mark VIII', '70802.91');
insert into car (make, model, price) values ('Honda', 'Civic', '44742.90');
insert into car (make, model, price) values ('Lamborghini', 'Diablo', '3145.04');
insert into car (make, model, price) values ('Dodge', 'Ram 3500', '61229.09');
insert into car (make, model, price) values ('GMC', 'Savana 3500', '83662.72');
insert into car (make, model, price) values ('Buick', 'Estate', '25512.24');
insert into car (make, model, price) values ('Subaru', 'Outback', '96887.30');
insert into car (make, model, price) values ('Pontiac', 'Solstice', '32996.37');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '33203.63');
insert into car (make, model, price) values ('GMC', 'Sierra', '36953.80');
insert into car (make, model, price) values ('Lexus', 'LS', '88776.48');
insert into car (make, model, price) values ('BMW', '325', '22046.21');
insert into car (make, model, price) values ('Mitsubishi', 'Tredia', '24258.76');
insert into car (make, model, price) values ('BMW', 'X5', '47287.40');
insert into car (make, model, price) values ('Maserati', 'GranTurismo', '20329.83');
insert into car (make, model, price) values ('Volkswagen', 'Golf III', '55916.80');
insert into car (make, model, price) values ('Mercury', 'Villager', '93951.53');
insert into car (make, model, price) values ('Mazda', 'Familia', '2444.65');
insert into car (make, model, price) values ('Porsche', 'Boxster', '13900.34');
insert into car (make, model, price) values ('Chevrolet', 'Express', '51815.30');
insert into car (make, model, price) values ('Mercury', 'Cougar', '49305.50');
insert into car (make, model, price) values ('Lexus', 'IS', '56207.81');
insert into car (make, model, price) values ('Mitsubishi', 'Challenger', '60452.26');
insert into car (make, model, price) values ('GMC', 'Sierra 2500', '40719.01');
insert into car (make, model, price) values ('Volvo', 'C30', '98268.27');
insert into car (make, model, price) values ('GMC', 'Safari', '6099.03');
insert into car (make, model, price) values ('Saturn', 'L-Series', '16160.24');
insert into car (make, model, price) values ('Dodge', 'Viper', '41538.30');
insert into car (make, model, price) values ('Chrysler', 'LHS', '44941.08');
insert into car (make, model, price) values ('Isuzu', 'Space', '18138.17');
insert into car (make, model, price) values ('Hyundai', 'Veracruz', '99311.01');
insert into car (make, model, price) values ('Pontiac', 'Firefly', '46694.51');
insert into car (make, model, price) values ('Infiniti', 'Q', '85429.70');
insert into car (make, model, price) values ('Pontiac', 'G6', '33947.53');
insert into car (make, model, price) values ('Ford', 'F350', '42097.19');
insert into car (make, model, price) values ('Audi', 'A4', '87561.98');
insert into car (make, model, price) values ('Isuzu', 'Rodeo', '44795.87');
insert into car (make, model, price) values ('Pontiac', 'Trans Sport', '31201.83');
insert into car (make, model, price) values ('GMC', 'Sierra', '11172.16');
insert into car (make, model, price) values ('Honda', 'CR-V', '8305.24');
insert into car (make, model, price) values ('BMW', '3 Series', '39050.03');
insert into car (make, model, price) values ('Saturn', 'VUE', '56552.06');
insert into car (make, model, price) values ('Ford', 'Freestyle', '65785.54');
insert into car (make, model, price) values ('Maybach', '62', '90090.42');
insert into car (make, model, price) values ('Mitsubishi', 'Outlander', '4554.25');
insert into car (make, model, price) values ('Toyota', 'Corolla', '19878.44');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '39164.39');
insert into car (make, model, price) values ('Buick', 'Park Avenue', '87507.26');
insert into car (make, model, price) values ('Mercedes-Benz', '600SEC', '72965.80');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '4379.55');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '35929.30');
insert into car (make, model, price) values ('Nissan', 'Quest', '83937.10');
insert into car (make, model, price) values ('Lincoln', 'Mark VIII', '60841.70');
insert into car (make, model, price) values ('Pontiac', 'Sunbird', '93041.59');
insert into car (make, model, price) values ('Ford', 'Club Wagon', '51483.39');
insert into car (make, model, price) values ('Buick', 'Somerset', '25926.06');
insert into car (make, model, price) values ('Mazda', 'Mazdaspeed 3', '79483.09');
insert into car (make, model, price) values ('Cadillac', 'Escalade', '16558.90');
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', '90192.19');
insert into car (make, model, price) values ('Subaru', 'Leone', '64293.50');
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', '63924.16');
insert into car (make, model, price) values ('Honda', 'Accord Crosstour', '27181.44');
insert into car (make, model, price) values ('Chevrolet', 'Aveo', '16118.88');
insert into car (make, model, price) values ('Dodge', 'Viper', '68537.75');
insert into car (make, model, price) values ('Mercedes-Benz', 'Sprinter 2500', '31655.83');
insert into car (make, model, price) values ('Jaguar', 'XJ Series', '14214.41');
insert into car (make, model, price) values ('Porsche', 'Boxster', '15764.54');
insert into car (make, model, price) values ('Maserati', 'Quattroporte', '51713.71');
insert into car (make, model, price) values ('Mitsubishi', 'Diamante', '26676.46');
insert into car (make, model, price) values ('GMC', '2500 Club Coupe', '49034.57');
insert into car (make, model, price) values ('Cadillac', 'STS-V', '13385.02');
insert into car (make, model, price) values ('GMC', 'Suburban 2500', '88961.53');
insert into car (make, model, price) values ('Volkswagen', 'Type 2', '90146.28');
insert into car (make, model, price) values ('Volvo', 'XC60', '90842.45');
insert into car (make, model, price) values ('Maserati', 'Spyder', '41015.70');
insert into car (make, model, price) values ('Volkswagen', 'Golf III', '15235.39');
insert into car (make, model, price) values ('Land Rover', 'Defender', '18960.50');
insert into car (make, model, price) values ('Lincoln', 'Continental', '20176.01');
insert into car (make, model, price) values ('Volkswagen', 'New Beetle', '72536.17');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '78495.14');
insert into car (make, model, price) values ('Toyota', 'Prius Plug-in Hybrid', '11153.12');
insert into car (make, model, price) values ('Buick', 'Regal', '67929.67');
insert into car (make, model, price) values ('Chrysler', '300', '88529.51');
insert into car (make, model, price) values ('Chevrolet', 'Metro', '22165.32');
insert into car (make, model, price) values ('Lincoln', 'Continental', '71791.28');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '64146.39');
insert into car (make, model, price) values ('Acura', 'TL', '18297.06');
insert into car (make, model, price) values ('Pontiac', 'GTO', '3124.03');
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', '45702.43');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 2500', '83640.65');
insert into car (make, model, price) values ('Jeep', 'Liberty', '26105.62');
insert into car (make, model, price) values ('Chrysler', 'Crossfire Roadster', '37232.88');
insert into car (make, model, price) values ('Volkswagen', 'Scirocco', '20120.12');
insert into car (make, model, price) values ('Volvo', 'S40', '59900.82');
insert into car (make, model, price) values ('Ford', 'Mustang', '43027.92');
insert into car (make, model, price) values ('Mitsubishi', 'Endeavor', '3868.00');
insert into car (make, model, price) values ('Pontiac', 'Trans Sport', '53569.67');
insert into car (make, model, price) values ('Dodge', 'Viper', '38156.18');
insert into car (make, model, price) values ('Infiniti', 'M', '24920.61');
insert into car (make, model, price) values ('BMW', '525', '6816.16');
insert into car (make, model, price) values ('Pontiac', 'LeMans', '21272.90');
insert into car (make, model, price) values ('Saturn', 'Relay', '24202.77');
insert into car (make, model, price) values ('Audi', 'A4', '49687.04');
insert into car (make, model, price) values ('Kia', 'Sephia', '38800.95');
insert into car (make, model, price) values ('Kia', 'Soul', '9033.84');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '90676.71');
insert into car (make, model, price) values ('Suzuki', 'XL7', '80464.81');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '95475.43');
insert into car (make, model, price) values ('Ford', 'Th!nk', '5700.11');
insert into car (make, model, price) values ('Mercury', 'Cougar', '38532.89');
insert into car (make, model, price) values ('Plymouth', 'Breeze', '39630.99');
insert into car (make, model, price) values ('GMC', 'Jimmy', '17795.15');
insert into car (make, model, price) values ('Toyota', 'Avalon', '15209.25');
insert into car (make, model, price) values ('Geo', 'Metro', '44717.20');
insert into car (make, model, price) values ('Subaru', 'Outback', '5159.30');
insert into car (make, model, price) values ('Hummer', 'H1', '92465.58');
insert into car (make, model, price) values ('Acura', 'CL', '73545.67');
insert into car (make, model, price) values ('Nissan', 'Sentra', '57000.27');
insert into car (make, model, price) values ('Ford', 'Expedition', '61609.41');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '30732.97');
insert into car (make, model, price) values ('Chevrolet', 'Caprice', '63140.06');
insert into car (make, model, price) values ('Chevrolet', 'Express', '79376.28');
insert into car (make, model, price) values ('Jeep', 'Compass', '65941.22');
insert into car (make, model, price) values ('Nissan', 'Frontier', '13600.58');
insert into car (make, model, price) values ('Mercedes-Benz', 'W201', '31372.79');
insert into car (make, model, price) values ('Ford', 'Th!nk', '88853.05');
insert into car (make, model, price) values ('Volvo', 'XC60', '95266.93');
insert into car (make, model, price) values ('Infiniti', 'EX', '15779.46');
insert into car (make, model, price) values ('Daewoo', 'Lanos', '71263.87');
insert into car (make, model, price) values ('Lincoln', 'Navigator L', '73281.89');
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', '6524.23');
insert into car (make, model, price) values ('Kia', 'Rio', '37783.95');
insert into car (make, model, price) values ('Lexus', 'LS', '49852.22');
insert into car (make, model, price) values ('Volkswagen', 'Fox', '4557.44');
insert into car (make, model, price) values ('Lexus', 'IS', '36515.06');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '53727.36');
insert into car (make, model, price) values ('BMW', 'X6', '55277.07');
insert into car (make, model, price) values ('Mitsubishi', 'Space', '57098.06');
insert into car (make, model, price) values ('BMW', '325', '68299.08');
insert into car (make, model, price) values ('Toyota', 'Solara', '4935.50');
insert into car (make, model, price) values ('Honda', 'Fit', '26844.89');
insert into car (make, model, price) values ('Lotus', 'Exige', '12515.95');
insert into car (make, model, price) values ('Panoz', 'Esperante', '44331.09');
insert into car (make, model, price) values ('BMW', 'X3', '50779.98');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '95900.41');
insert into car (make, model, price) values ('Mazda', '626', '5803.37');
insert into car (make, model, price) values ('Ford', 'F-Series', '83055.60');
insert into car (make, model, price) values ('Ford', 'E-Series', '41888.71');
insert into car (make, model, price) values ('Lexus', 'ES', '34886.13');
insert into car (make, model, price) values ('Lamborghini', 'Diablo', '74544.67');
insert into car (make, model, price) values ('Plymouth', 'Voyager', '76014.03');
insert into car (make, model, price) values ('BMW', '5 Series', '53425.76');
insert into car (make, model, price) values ('Chevrolet', 'Impala', '19221.95');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', '49410.20');
insert into car (make, model, price) values ('Honda', 'Accord', '38260.30');
insert into car (make, model, price) values ('GMC', 'Savana 3500', '75192.50');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '21942.79');
insert into car (make, model, price) values ('Toyota', 'Sequoia', '53512.37');
insert into car (make, model, price) values ('Nissan', '350Z Roadster', '50331.44');
insert into car (make, model, price) values ('Mercedes-Benz', 'CLK-Class', '6891.48');
insert into car (make, model, price) values ('Honda', 'Pilot', '8276.80');
insert into car (make, model, price) values ('Volkswagen', 'Eos', '5546.83');
insert into car (make, model, price) values ('Lexus', 'IS-F', '56118.38');
insert into car (make, model, price) values ('Lexus', 'RX Hybrid', '17839.45');
insert into car (make, model, price) values ('Dodge', 'Ram 2500 Club', '31620.15');
insert into car (make, model, price) values ('Mazda', 'MPV', '73151.42');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '60525.08');
insert into car (make, model, price) values ('Hyundai', 'Tiburon', '20459.13');
insert into car (make, model, price) values ('Honda', 'Civic', '76037.01');
insert into car (make, model, price) values ('Mazda', 'MX-5', '84394.47');
insert into car (make, model, price) values ('Ford', 'Focus', '82117.55');
insert into car (make, model, price) values ('Mitsubishi', 'Mighty Max Macro', '57387.28');
insert into car (make, model, price) values ('Pontiac', 'GTO', '48649.66');
insert into car (make, model, price) values ('Buick', 'Somerset', '3525.84');
insert into car (make, model, price) values ('Hyundai', 'Tucson', '37627.99');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '20353.81');
insert into car (make, model, price) values ('Porsche', 'Boxster', '67240.39');
insert into car (make, model, price) values ('Mercedes-Benz', 'G-Class', '11198.09');
insert into car (make, model, price) values ('Infiniti', 'G', '87002.31');
insert into car (make, model, price) values ('Lexus', 'ES', '59376.05');
insert into car (make, model, price) values ('Ford', 'Falcon', '81731.69');
insert into car (make, model, price) values ('Lotus', 'Esprit', '67683.38');
insert into car (make, model, price) values ('Cadillac', 'XLR', '71183.22');
insert into car (make, model, price) values ('Buick', 'Riviera', '24811.51');
insert into car (make, model, price) values ('Lamborghini', 'Countach', '9645.98');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '88274.76');
insert into car (make, model, price) values ('Nissan', 'Maxima', '93104.63');
insert into car (make, model, price) values ('Ford', 'E-Series', '99853.34');
insert into car (make, model, price) values ('Aston Martin', 'DB9', '91430.77');
insert into car (make, model, price) values ('Suzuki', 'Samurai', '23834.96');
insert into car (make, model, price) values ('Buick', 'Regal', '9993.08');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', '95664.40');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '17079.79');
insert into car (make, model, price) values ('Bentley', 'Brooklands', '32411.02');
insert into car (make, model, price) values ('Chevrolet', 'Express 2500', '69087.60');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '13211.35');
insert into car (make, model, price) values ('Volvo', 'XC70', '83615.58');
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', '45504.84');
insert into car (make, model, price) values ('Ford', 'Freestar', '3920.29');
insert into car (make, model, price) values ('Subaru', 'Outback', '51525.37');
insert into car (make, model, price) values ('Volvo', 'V50', '28674.47');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '48411.36');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '23734.54');
insert into car (make, model, price) values ('Nissan', 'Cube', '91441.26');
insert into car (make, model, price) values ('Volvo', 'V50', '83738.92');
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', '9855.82');
insert into car (make, model, price) values ('Saturn', 'VUE', '49416.11');
insert into car (make, model, price) values ('Lexus', 'LS', '71793.87');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '52461.77');
insert into car (make, model, price) values ('Chevrolet', 'G-Series 3500', '43704.09');
insert into car (make, model, price) values ('Volkswagen', 'Routan', '84907.83');
insert into car (make, model, price) values ('Ford', 'Econoline E250', '79888.34');
insert into car (make, model, price) values ('GMC', 'Sierra 2500', '63879.77');
insert into car (make, model, price) values ('BMW', '5 Series', '38967.40');
insert into car (make, model, price) values ('Cadillac', 'STS', '74255.28');
insert into car (make, model, price) values ('Oldsmobile', 'Intrigue', '71757.56');
insert into car (make, model, price) values ('Toyota', 'Sequoia', '48883.11');
insert into car (make, model, price) values ('Kia', 'Rio', '44433.26');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '8974.87');
insert into car (make, model, price) values ('Ford', 'Th!nk', '31943.31');
insert into car (make, model, price) values ('Suzuki', 'XL-7', '47391.48');
insert into car (make, model, price) values ('Kia', 'Mohave/Borrego', '85696.48');
insert into car (make, model, price) values ('Subaru', 'Brat', '48807.21');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '9164.85');
insert into car (make, model, price) values ('Lexus', 'SC', '64978.48');
insert into car (make, model, price) values ('Cadillac', 'Eldorado', '84259.92');
insert into car (make, model, price) values ('Bentley', 'Continental', '24192.28');
insert into car (make, model, price) values ('GMC', 'Yukon XL 2500', '21524.31');
insert into car (make, model, price) values ('Suzuki', 'Forenza', '73524.70');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '43320.23');
insert into car (make, model, price) values ('Cadillac', 'Escalade', '17110.99');
insert into car (make, model, price) values ('Honda', 'Accord', '77666.32');
insert into car (make, model, price) values ('GMC', 'Yukon XL 2500', '76831.91');
insert into car (make, model, price) values ('MINI', 'Cooper', '61459.45');
insert into car (make, model, price) values ('Ford', 'Mustang', '70344.29');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '73703.29');
insert into car (make, model, price) values ('Hyundai', 'Tiburon', '41186.81');
insert into car (make, model, price) values ('Acura', 'RL', '95100.07');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '14067.43');
insert into car (make, model, price) values ('Mazda', 'B-Series', '50136.34');
insert into car (make, model, price) values ('Ford', 'Mustang', '53467.56');
insert into car (make, model, price) values ('Audi', 'V8', '89740.42');
insert into car (make, model, price) values ('Eagle', 'Talon', '36081.55');
insert into car (make, model, price) values ('Ford', 'Probe', '60842.48');
insert into car (make, model, price) values ('Plymouth', 'Breeze', '74818.13');
insert into car (make, model, price) values ('Mitsubishi', 'Mighty Max', '18106.84');
insert into car (make, model, price) values ('Bentley', 'Continental', '87336.75');
insert into car (make, model, price) values ('Eagle', 'Summit', '86420.13');
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', '83436.14');
insert into car (make, model, price) values ('Chevrolet', 'S10 Blazer', '18968.46');
insert into car (make, model, price) values ('Oldsmobile', 'Aurora', '55298.61');
insert into car (make, model, price) values ('Buick', 'Century', '20355.11');
insert into car (make, model, price) values ('Dodge', 'Intrepid', '69720.89');
insert into car (make, model, price) values ('Dodge', 'Nitro', '50763.69');
insert into car (make, model, price) values ('Chevrolet', 'Colorado', '55825.35');
insert into car (make, model, price) values ('Subaru', 'Brat', '35272.16');
insert into car (make, model, price) values ('Ford', 'Ranger', '59503.36');
insert into car (make, model, price) values ('Kia', 'Optima', '7473.56');
insert into car (make, model, price) values ('Land Rover', 'Defender 90', '22363.09');
insert into car (make, model, price) values ('Chevrolet', '1500', '47723.18');
insert into car (make, model, price) values ('Porsche', '968', '86633.81');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '31747.08');
insert into car (make, model, price) values ('Nissan', 'Sentra', '27848.81');
insert into car (make, model, price) values ('Eagle', 'Summit', '21341.99');
insert into car (make, model, price) values ('Mazda', 'MX-5', '12585.25');
insert into car (make, model, price) values ('Lincoln', 'Continental', '84617.34');
insert into car (make, model, price) values ('Dodge', 'Durango', '96704.96');
insert into car (make, model, price) values ('BMW', '6 Series', '56718.20');
insert into car (make, model, price) values ('MINI', 'Cooper Clubman', '98469.97');
insert into car (make, model, price) values ('Buick', 'Skylark', '91474.62');
insert into car (make, model, price) values ('Dodge', 'Ram 2500 Club', '28362.85');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '15474.84');
insert into car (make, model, price) values ('Infiniti', 'I', '23265.71');
insert into car (make, model, price) values ('BMW', '545', '18403.98');
insert into car (make, model, price) values ('Dodge', 'Shadow', '29850.81');
insert into car (make, model, price) values ('Lincoln', 'MKS', '30219.15');
insert into car (make, model, price) values ('Toyota', 'T100 Xtra', '45547.09');
insert into car (make, model, price) values ('Mercedes-Benz', 'G-Class', '27309.38');
insert into car (make, model, price) values ('Toyota', 'FJ Cruiser', '36365.40');
insert into car (make, model, price) values ('GMC', 'Acadia', '83324.06');
insert into car (make, model, price) values ('Kia', 'Sedona', '26819.37');
insert into car (make, model, price) values ('Dodge', 'Ram', '39472.32');
insert into car (make, model, price) values ('Nissan', '240SX', '13530.53');
insert into car (make, model, price) values ('Lexus', 'RX', '58779.40');
insert into car (make, model, price) values ('Pontiac', 'Safari', '96860.68');
insert into car (make, model, price) values ('Maybach', '57', '26711.73');
insert into car (make, model, price) values ('Dodge', 'Dakota', '3001.02');
insert into car (make, model, price) values ('Chevrolet', 'Malibu', '37000.82');
insert into car (make, model, price) values ('BMW', 'Z8', '98949.60');
insert into car (make, model, price) values ('Maybach', '62', '60988.07');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '91414.13');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '9077.23');
insert into car (make, model, price) values ('Toyota', 'Avalon', '68029.53');
insert into car (make, model, price) values ('Toyota', 'RAV4', '39346.89');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '91694.55');
insert into car (make, model, price) values ('Plymouth', 'Grand Voyager', '38289.06');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '49073.55');
insert into car (make, model, price) values ('Mercury', 'Villager', '40683.43');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '34914.44');
insert into car (make, model, price) values ('Infiniti', 'FX', '69875.86');
insert into car (make, model, price) values ('Chrysler', 'Fifth Ave', '3446.14');
insert into car (make, model, price) values ('Hyundai', 'Accent', '39240.17');
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', '84342.15');
insert into car (make, model, price) values ('Plymouth', 'Prowler', '34300.14');
insert into car (make, model, price) values ('Oldsmobile', 'Achieva', '17951.23');
insert into car (make, model, price) values ('Mazda', 'MX-5', '63681.66');
insert into car (make, model, price) values ('Ford', 'Econoline E250', '64838.42');
insert into car (make, model, price) values ('Chevrolet', 'Citation', '29747.23');
insert into car (make, model, price) values ('Chevrolet', '2500', '79195.57');
insert into car (make, model, price) values ('BMW', 'M3', '47427.18');
insert into car (make, model, price) values ('Saturn', 'Relay', '82401.55');
insert into car (make, model, price) values ('Mazda', 'B-Series', '95864.60');
insert into car (make, model, price) values ('Mercury', 'Mountaineer', '90791.66');
insert into car (make, model, price) values ('Jaguar', 'XJ', '14893.88');
insert into car (make, model, price) values ('Ford', 'E250', '6441.51');
insert into car (make, model, price) values ('Mercedes-Benz', '600SEC', '18434.43');
insert into car (make, model, price) values ('Cadillac', 'DeVille', '17702.58');
insert into car (make, model, price) values ('Ford', 'F250', '89022.56');
insert into car (make, model, price) values ('Toyota', 'Matrix', '78204.02');
insert into car (make, model, price) values ('BMW', '750', '82749.31');
insert into car (make, model, price) values ('Toyota', 'Previa', '33475.86');
insert into car (make, model, price) values ('Maserati', 'GranSport', '13435.62');
insert into car (make, model, price) values ('Toyota', 'Prius', '48705.96');
insert into car (make, model, price) values ('Volvo', 'S80', '84191.30');
insert into car (make, model, price) values ('Hyundai', 'Tiburon', '62364.90');
insert into car (make, model, price) values ('Plymouth', 'Colt', '39082.88');
insert into car (make, model, price) values ('Jaguar', 'XF', '38408.43');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '80169.77');
insert into car (make, model, price) values ('BMW', '545', '83448.56');
insert into car (make, model, price) values ('Toyota', 'Sequoia', '85208.04');
insert into car (make, model, price) values ('Dodge', 'Charger', '75177.39');
insert into car (make, model, price) values ('Hyundai', 'Genesis Coupe', '59280.58');
insert into car (make, model, price) values ('Toyota', 'Tundra', '20924.86');
insert into car (make, model, price) values ('Oldsmobile', 'Bravada', '62190.90');
insert into car (make, model, price) values ('Dodge', 'Ram Wagon B250', '68787.28');
insert into car (make, model, price) values ('Lamborghini', 'Diablo', '12382.81');
insert into car (make, model, price) values ('Chevrolet', 'Express 2500', '74297.45');
insert into car (make, model, price) values ('Pontiac', 'GTO', '51476.20');
insert into car (make, model, price) values ('Chevrolet', 'S10', '67050.79');
insert into car (make, model, price) values ('Chrysler', 'PT Cruiser', '69204.63');
insert into car (make, model, price) values ('Subaru', 'Leone', '84936.42');
insert into car (make, model, price) values ('Mercury', 'Cougar', '74581.22');
insert into car (make, model, price) values ('Suzuki', 'Aerio', '64580.41');
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass', '9994.66');
insert into car (make, model, price) values ('Plymouth', 'Voyager', '94539.84');
insert into car (make, model, price) values ('Volvo', '960', '54809.82');
insert into car (make, model, price) values ('Toyota', 'Avalon', '7232.66');
insert into car (make, model, price) values ('Ford', 'F-Series Super Duty', '44354.24');
insert into car (make, model, price) values ('Mitsubishi', 'Montero', '97480.97');
insert into car (make, model, price) values ('Oldsmobile', 'Bravada', '10468.43');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '73039.43');
insert into car (make, model, price) values ('Dodge', 'Stratus', '27757.78');
insert into car (make, model, price) values ('Lexus', 'RX Hybrid', '3036.84');
insert into car (make, model, price) values ('Pontiac', 'Sunbird', '81366.62');
insert into car (make, model, price) values ('Ford', 'Fusion', '65223.18');
insert into car (make, model, price) values ('MINI', 'Cooper', '77743.07');
insert into car (make, model, price) values ('Volkswagen', 'R32', '49228.54');
insert into car (make, model, price) values ('Cadillac', 'CTS-V', '93724.52');
insert into car (make, model, price) values ('Dodge', 'Caliber', '70475.92');
insert into car (make, model, price) values ('Lamborghini', 'Gallardo', '84338.95');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '53911.82');
insert into car (make, model, price) values ('Dodge', 'Ram 2500', '17144.01');
insert into car (make, model, price) values ('Kia', 'Spectra', '98411.57');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '49480.33');
insert into car (make, model, price) values ('Volvo', 'S40', '97421.18');
insert into car (make, model, price) values ('Dodge', 'Magnum', '9487.19');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '87170.70');
insert into car (make, model, price) values ('Cadillac', 'Seville', '74203.88');
insert into car (make, model, price) values ('GMC', 'Savana 1500', '34366.42');
insert into car (make, model, price) values ('Nissan', 'Xterra', '74872.92');
insert into car (make, model, price) values ('Honda', 'CR-X', '3682.70');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '96995.24');
insert into car (make, model, price) values ('Mitsubishi', 'Montero Sport', '73387.83');
insert into car (make, model, price) values ('Pontiac', '6000', '53405.02');
insert into car (make, model, price) values ('Pontiac', 'Sunbird', '14889.97');
insert into car (make, model, price) values ('GMC', '3500', '72685.97');
insert into car (make, model, price) values ('Audi', 'riolet', '61869.92');
insert into car (make, model, price) values ('BMW', '325', '93062.09');
insert into car (make, model, price) values ('Chevrolet', 'G-Series 3500', '79448.21');
insert into car (make, model, price) values ('Toyota', 'Camry Solara', '87469.35');
insert into car (make, model, price) values ('Suzuki', 'Vitara', '5717.58');
insert into car (make, model, price) values ('Lexus', 'IS', '82901.71');
insert into car (make, model, price) values ('Pontiac', 'GTO', '6195.20');
insert into car (make, model, price) values ('Audi', 'A3', '20874.47');
insert into car (make, model, price) values ('Ford', 'Laser', '28026.82');
insert into car (make, model, price) values ('Chevrolet', 'Equinox', '2677.34');
insert into car (make, model, price) values ('Mitsubishi', 'Precis', '79379.54');
insert into car (make, model, price) values ('Panoz', 'Esperante', '12710.22');
insert into car (make, model, price) values ('Porsche', 'Cayenne', '85120.57');
insert into car (make, model, price) values ('Lincoln', 'MKX', '89118.30');
insert into car (make, model, price) values ('Subaru', 'Legacy', '45241.76');
insert into car (make, model, price) values ('Land Rover', 'Defender', '73995.86');
insert into car (make, model, price) values ('GMC', 'Savana', '35661.47');
insert into car (make, model, price) values ('Nissan', '350Z', '2462.70');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '24983.83');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '71767.06');
insert into car (make, model, price) values ('GMC', '2500', '65655.40');
insert into car (make, model, price) values ('Toyota', 'Celica', '41597.13');
insert into car (make, model, price) values ('Cadillac', 'SRX', '44422.60');
insert into car (make, model, price) values ('Mazda', 'CX-5', '8360.18');
insert into car (make, model, price) values ('Mitsubishi', 'Cordia', '79909.36');
insert into car (make, model, price) values ('GMC', 'Yukon', '79176.37');
insert into car (make, model, price) values ('GMC', 'Vandura G3500', '33262.09');
insert into car (make, model, price) values ('Buick', 'Regal', '65878.71');
insert into car (make, model, price) values ('BMW', '7 Series', '86684.24');
insert into car (make, model, price) values ('Ford', 'F150', '65473.95');
insert into car (make, model, price) values ('Corbin', 'Sparrow', '34156.53');
insert into car (make, model, price) values ('Lotus', 'Esprit', '73276.11');
insert into car (make, model, price) values ('Nissan', 'Altima', '37084.58');
insert into car (make, model, price) values ('Dodge', 'Nitro', '97521.58');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 3500', '74545.43');
insert into car (make, model, price) values ('BMW', '330', '49535.57');
insert into car (make, model, price) values ('GMC', 'Envoy XL', '62346.61');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '68885.76');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '19102.34');
insert into car (make, model, price) values ('Lexus', 'RX Hybrid', '20734.11');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '5987.98');
insert into car (make, model, price) values ('Cadillac', 'CTS', '29954.66');
insert into car (make, model, price) values ('Pontiac', 'Solstice', '70292.72');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', '23755.15');
insert into car (make, model, price) values ('Honda', 'Element', '59648.17');
insert into car (make, model, price) values ('Mazda', 'B-Series', '19877.61');
insert into car (make, model, price) values ('Dodge', 'Avenger', '90854.52');
insert into car (make, model, price) values ('Toyota', 'Avalon', '32967.64');
insert into car (make, model, price) values ('Volvo', 'S60', '3152.74');
insert into car (make, model, price) values ('Mercury', 'Sable', '64496.93');
insert into car (make, model, price) values ('Infiniti', 'Q', '23668.15');
insert into car (make, model, price) values ('Volvo', 'C70', '63752.67');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '48179.47');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 2500', '73762.44');
insert into car (make, model, price) values ('Subaru', 'Forester', '96838.66');
insert into car (make, model, price) values ('Saab', '9-5', '76142.72');
insert into car (make, model, price) values ('Dodge', 'Ram 3500', '19383.51');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '90639.76');
insert into car (make, model, price) values ('Honda', 'CR-V', '70409.33');
insert into car (make, model, price) values ('Mazda', 'MX-5', '88701.80');
insert into car (make, model, price) values ('Kia', 'Optima', '28977.16');
insert into car (make, model, price) values ('Nissan', 'Versa', '73474.25');
insert into car (make, model, price) values ('Dodge', 'Caravan', '33621.13');
insert into car (make, model, price) values ('Scion', 'tC', '65799.00');
insert into car (make, model, price) values ('Volvo', 'C70', '2576.98');
